name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy-now:
        name: Deploy to Now.sh
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: ZEIT Now Deployment
              uses: amondnet/now-deployment@v2.0.1
              with:
                  zeit-token: ${{secrets.ZEIT_TOKEN}}
                  now-args: "--prod"
                  now-org-id: "CMEosGJWMqW6XpZMXt7dDjTN"
                  now-project-id: "QmPizhrgxjNf2WFj46SFCLdfh4NdKD3sRTzzEeWbAcXT81"
                  working-directory: ./clevel_app
