name: Publish Crates

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: 1.41.1
            - uses: thiagoarrais/action-cargo@master
            - run: |
                  cargo login $CRATES_AUTH_TOKEN
                  cargo publish
              env:
                  CRATES_AUTH_TOKEN: ${{secrets.CRATES_AUTH_TOKEN}}
