name: Publish GPR

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: 1.41.1
                  targets: wasm32-unknown-unknown
            - run: |
                  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - run: |
                  wasm-pack build
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: "@your-github-username"
            - run: |
                  cd pkg/
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
