name: Publish

on:
    push:
        branches:
            - master

jobs:
    publish-npm:
        name: Publish NPM
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: 1.41.1
                  targets: wasm32-unknown-unknown
            - run: |
                  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
            - run: |
                  wasm-pack build
            - run: |
                  cd pkg/
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    publish-crates:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: hecrj/setup-rust-action@v1
              with:
                  rust-version: 1.41.1
            - uses: thiagoarrais/action-cargo@master
            - run: |
                  cargo login $CRATES_AUTH_TOKEN
                  cargo publish --allow-dirty
              env:
                  CRATES_AUTH_TOKEN: ${{secrets.CRATES_AUTH_TOKEN}}
